/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lisztian' at '4/2/18 2:25 PM' with Gradle 3.0
 *
 * @author lisztian, @date 4/2/18 2:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
